{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "fr-CH",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/PC-ETAGE\\DATAEXPLOITATION;DWBugs",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "PC-ETAGE\\DATAEXPLOITATION",
            "database": "DWBugs"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "pc-etage\\dataexploitation;DWBugs",
          "Username": "sa",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "DimCalendar",
        "columns": [
          {
            "name": "DateId",
            "dataType": "int64",
            "sourceColumn": "DateId"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date"
          },
          {
            "name": "Day",
            "dataType": "int64",
            "sourceColumn": "Day"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/PC-ETAGE\\DATAEXPLOITATION;DWBugs\",",
                "    dbo_DimCalendar = Source{[Schema=\"dbo\",Item=\"DimCalendar\"]}[Data]",
                "in",
                "    dbo_DimCalendar"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "CalendarHierarchy",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Month"
              },
              {
                "name": "Day",
                "ordinal": 2,
                "column": "Day"
              }
            ]
          }
        ]
      },
      {
        "name": "DimCategory",
        "columns": [
          {
            "name": "CategoryId",
            "dataType": "int64",
            "sourceColumn": "CategoryId"
          },
          {
            "name": "CategoryName",
            "dataType": "string",
            "sourceColumn": "CategoryName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/PC-ETAGE\\DATAEXPLOITATION;DWBugs\",",
                "    dbo_DimCategory = Source{[Schema=\"dbo\",Item=\"DimCategory\"]}[Data]",
                "in",
                "    dbo_DimCategory"
              ]
            }
          }
        ]
      },
      {
        "name": "DimOs",
        "columns": [
          {
            "name": "OsId",
            "dataType": "int64",
            "sourceColumn": "OsId"
          },
          {
            "name": "OsPlatform",
            "dataType": "string",
            "sourceColumn": "OsPlatform"
          },
          {
            "name": "OsName",
            "dataType": "string",
            "sourceColumn": "OsName"
          },
          {
            "name": "OsVersion",
            "dataType": "string",
            "sourceColumn": "OsVersion"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/PC-ETAGE\\DATAEXPLOITATION;DWBugs\",",
                "    dbo_DimOs = Source{[Schema=\"dbo\",Item=\"DimOs\"]}[Data]",
                "in",
                "    dbo_DimOs"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "OsHierarchy",
            "levels": [
              {
                "name": "OsPlatform",
                "ordinal": 0,
                "column": "OsPlatform"
              },
              {
                "name": "OsName",
                "ordinal": 1,
                "column": "OsName"
              },
              {
                "name": "OsVersion",
                "ordinal": 2,
                "column": "OsVersion"
              }
            ]
          }
        ]
      },
      {
        "name": "DimPriority",
        "columns": [
          {
            "name": "PriorityId",
            "dataType": "int64",
            "sourceColumn": "PriorityId"
          },
          {
            "name": "PriorityName",
            "dataType": "string",
            "sourceColumn": "PriorityName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/PC-ETAGE\\DATAEXPLOITATION;DWBugs\",",
                "    dbo_DimPriority = Source{[Schema=\"dbo\",Item=\"DimPriority\"]}[Data]",
                "in",
                "    dbo_DimPriority"
              ]
            }
          }
        ]
      },
      {
        "name": "DimProject",
        "columns": [
          {
            "name": "ProjectId",
            "dataType": "int64",
            "sourceColumn": "ProjectId"
          },
          {
            "name": "ProjectName",
            "dataType": "string",
            "sourceColumn": "ProjectName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/PC-ETAGE\\DATAEXPLOITATION;DWBugs\",",
                "    dbo_DimProject = Source{[Schema=\"dbo\",Item=\"DimProject\"]}[Data]",
                "in",
                "    dbo_DimProject"
              ]
            }
          }
        ]
      },
      {
        "name": "DimReproducibility",
        "columns": [
          {
            "name": "ReproducibilityId",
            "dataType": "int64",
            "sourceColumn": "ReproducibilityId"
          },
          {
            "name": "ReproducibilityName",
            "dataType": "string",
            "sourceColumn": "ReproducibilityName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/PC-ETAGE\\DATAEXPLOITATION;DWBugs\",",
                "    dbo_DimReproducibility = Source{[Schema=\"dbo\",Item=\"DimReproducibility\"]}[Data]",
                "in",
                "    dbo_DimReproducibility"
              ]
            }
          }
        ]
      },
      {
        "name": "DimSeverity",
        "columns": [
          {
            "name": "SeverityId",
            "dataType": "int64",
            "sourceColumn": "SeverityId"
          },
          {
            "name": "SeverityName",
            "dataType": "string",
            "sourceColumn": "SeverityName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/PC-ETAGE\\DATAEXPLOITATION;DWBugs\",",
                "    dbo_DimSeverity = Source{[Schema=\"dbo\",Item=\"DimSeverity\"]}[Data]",
                "in",
                "    dbo_DimSeverity"
              ]
            }
          }
        ]
      },
      {
        "name": "DimStatus",
        "columns": [
          {
            "name": "StatusId",
            "dataType": "int64",
            "sourceColumn": "StatusId"
          },
          {
            "name": "StatusName",
            "dataType": "string",
            "sourceColumn": "StatusName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/PC-ETAGE\\DATAEXPLOITATION;DWBugs\",",
                "    dbo_DimStatus = Source{[Schema=\"dbo\",Item=\"DimStatus\"]}[Data]",
                "in",
                "    dbo_DimStatus"
              ]
            }
          }
        ]
      },
      {
        "name": "DimUser",
        "columns": [
          {
            "name": "UserId",
            "dataType": "int64",
            "sourceColumn": "UserId"
          },
          {
            "name": "Username",
            "dataType": "string",
            "sourceColumn": "Username"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/PC-ETAGE\\DATAEXPLOITATION;DWBugs\",",
                "    dbo_DimUser = Source{[Schema=\"dbo\",Item=\"DimUser\"]}[Data]",
                "in",
                "    dbo_DimUser"
              ]
            }
          }
        ]
      },
      {
        "name": "DimVersion",
        "columns": [
          {
            "name": "VersionId",
            "dataType": "int64",
            "sourceColumn": "VersionId"
          },
          {
            "name": "VersionName",
            "dataType": "string",
            "sourceColumn": "VersionName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/PC-ETAGE\\DATAEXPLOITATION;DWBugs\",",
                "    dbo_DimVersion = Source{[Schema=\"dbo\",Item=\"DimVersion\"]}[Data]",
                "in",
                "    dbo_DimVersion"
              ]
            }
          }
        ]
      },
      {
        "name": "FactBug",
        "columns": [
          {
            "name": "BugFactKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BugFactKey"
          },
          {
            "name": "BugId",
            "dataType": "int64",
            "sourceColumn": "BugId"
          },
          {
            "name": "SDC_StartDate",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SDC_StartDate"
          },
          {
            "name": "SDC_EndDate",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SDC_EndDate"
          },
          {
            "name": "IsCurrent",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsCurrent"
          },
          {
            "name": "Summary",
            "dataType": "string",
            "sourceColumn": "Summary"
          },
          {
            "name": "DateSubmittedId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateSubmittedId"
          },
          {
            "name": "DateUpdatedId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateUpdatedId"
          },
          {
            "name": "ProjectId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProjectId"
          },
          {
            "name": "ReporterId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ReporterId"
          },
          {
            "name": "AssigneeId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AssigneeId"
          },
          {
            "name": "PriorityId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PriorityId"
          },
          {
            "name": "SeverityId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SeverityId"
          },
          {
            "name": "ReproducibilityId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ReproducibilityId"
          },
          {
            "name": "ProductVersionId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductVersionId"
          },
          {
            "name": "VersionFixedId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "VersionFixedId"
          },
          {
            "name": "CategoryId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CategoryId"
          },
          {
            "name": "OsId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OsId"
          },
          {
            "name": "ViewStatusId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ViewStatusId"
          },
          {
            "name": "StatusId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StatusId"
          },
          {
            "name": "ResolutionId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ResolutionId"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/PC-ETAGE\\DATAEXPLOITATION;DWBugs\",",
                "    dbo_FactBug = Source{[Schema=\"dbo\",Item=\"FactBug\"]}[Data]",
                "in",
                "    dbo_FactBug"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Number of bugs (Current)",
            "expression": [
              " ",
              "CALCULATE(",
              "    DISTINCTCOUNT(FactBug[BugId]),",
              "    FactBug[IsCurrent] = TRUE() ",
              ")"
            ]
          },
          {
            "name": "Bugs Assigned",
            "expression": [
              " ",
              "CALCULATE(",
              "    [Number of bugs (Current)],",
              "    FactBug[IsCurrent] = TRUE(),",
              "    FactBug[AssigneeId] <> 0",
              ")"
            ]
          },
          {
            "name": "Bugs Created",
            "expression": [
              " ",
              "CALCULATE(",
              "    [Number of bugs (Current)],",
              "    USERELATIONSHIP(FactBug[DateSubmittedId], DimCalendar[DateId])",
              ")"
            ]
          },
          {
            "name": "Open Bugs",
            "expression": [
              " ",
              "CALCULATE(",
              "    [Number of bugs (Current)],",
              "    USERELATIONSHIP(FactBug[ResolutionId], DimStatus[StatusId]),",
              "    NOT(DimStatus[StatusName] IN {",
              "        \"fixed\", ",
              "        \"resolved\", ",
              "        \"won't fix\", ",
              "        \"unable to reproduce\", ",
              "        \"no change required\"",
              "    })",
              ")"
            ]
          },
          {
            "name": "Bugs Resolved (Total)",
            "expression": [
              " ",
              "CALCULATE(",
              "    [Number of bugs (Current)],",
              "    USERELATIONSHIP(FactBug[ResolutionId], DimStatus[StatusId]),",
              "    DimStatus[StatusName] IN {",
              "        \"fixed\", ",
              "        \"resolved\", ",
              "        \"won't fix\", ",
              "        \"unable to reproduce\", ",
              "        \"no change required\"",
              "    }",
              ")"
            ]
          },
          {
            "name": "Number of changes (History)",
            "expression": " COUNTROWS(FactBug)"
          },
          {
            "name": "Bugs Fixed (Success)",
            "expression": [
              " ",
              "CALCULATE(",
              "    [Number of bugs (Current)],",
              "    USERELATIONSHIP(FactBug[ResolutionId], DimStatus[StatusId]),",
              "    DimStatus[StatusName] IN {\"fixed\", \"resolved\"}",
              ")"
            ]
          },
          {
            "name": "Bugs resolved (per developer)",
            "expression": [
              " ",
              "CALCULATE(",
              "    [Bugs Resolved (Total)],",
              "    FactBug[AssigneeId] <> 0 ",
              ")"
            ]
          },
          {
            "name": "Top Dev (Summary)",
            "expression": [
              " ",
              "VAR DevStats = ",
              "    ADDCOLUMNS(",
              "        VALUES(DimUser[UserId]),",
              "        \"UserName\", CALCULATE(MAX(DimUser[Username])),",
              "        \"NbResolved\", [Bugs resolved (per developer)],",
              "        \"AvgTime\", [Average resolution time (Days)]",
              "    )",
              "VAR DevFiltered = ",
              "    FILTER(",
              "        DevStats,",
              "        [NbResolved] > 0 && NOT ISBLANK([AvgTime])",
              "    )",
              "VAR BestDev = ",
              "    TOPN(",
              "        1,",
              "        DevFiltered,",
              "        [NbResolved], DESC, // Priorité au nombre de bugs",
              "        [AvgTime], ASC      // Puis à la vitesse (le plus petit temps est le mieux)",
              "    )",
              "VAR TheName = MAXX(BestDev, [UserName])",
              "VAR TheCount = MAXX(BestDev, [NbResolved])",
              "VAR TheTime = MAXX(BestDev, [AvgTime])",
              "",
              "RETURN ",
              "    IF(",
              "        ISBLANK(TheName),",
              "        \"Aucune donnée\",",
              "        TheName & \" : \" & FORMAT(TheCount, \"0\") & \" bugs (\" & FORMAT(TheTime, \"0.0\") & \" d/bug)\"",
              "    )"
            ]
          },
          {
            "name": "Rate Bug Correction (%)",
            "expression": [
              " ",
              "DIVIDE(",
              "    [Bugs Resolved (Total)],",
              "    [Bugs Created],",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "Avg Resolution Time (Hours)",
            "expression": " [Average resolution time (Days)] * 24"
          },
          {
            "name": "Average resolution time (Days)",
            "expression": [
              " ",
              "AVERAGEX(",
              "    FILTER(",
              "        FactBug,",
              "        FactBug[IsCurrent] = TRUE() && ",
              "        (",
              "            VAR ResStatus = CALCULATE(",
              "                SELECTEDVALUE(DimStatus[StatusName]), ",
              "                USERELATIONSHIP(FactBug[ResolutionId], DimStatus[StatusId])",
              "            )",
              "            RETURN ResStatus IN {\"fixed\", \"resolved\"}",
              "        ) &&",
              "        // --- SÉCURITÉ ANTI-1900 ---",
              "        FactBug[DateSubmittedId] <> 0 && ",
              "        FactBug[DateUpdatedId] <> 0 &&",
              "        FactBug[DateUpdatedId] >= FactBug[DateSubmittedId] // Protection contre les dates inversées",
              "    ),",
              "    ",
              "    // Calcul Mathématique (ID vers Date)",
              "    VAR StartID = FactBug[DateSubmittedId]",
              "    VAR EndID = FactBug[DateUpdatedId]",
              "    ",
              "    VAR StartDate = DATE(INT(StartID / 10000), INT(MOD(StartID, 10000) / 100), MOD(StartID, 100))",
              "    VAR EndDate =   DATE(INT(EndID / 10000),   INT(MOD(EndID, 10000) / 100),   MOD(EndID, 100))",
              "    ",
              "    VAR Ecart = DATEDIFF(StartDate, EndDate, DAY)",
              "    ",
              "    RETURN ",
              "    IF(Ecart = 0, 1, Ecart)",
              ")"
            ],
            "formatString": "0.00"
          },
          {
            "name": "Median resolution time",
            "expression": [
              " ",
              "MEDIANX(",
              "    FILTER(",
              "        FactBug,",
              "        FactBug[IsCurrent] = TRUE() && ",
              "        FactBug[DateSubmittedId] <> 0 && ",
              "        FactBug[DateUpdatedId] <> 0 &&",
              "        (",
              "            VAR ResStatus = CALCULATE(",
              "                SELECTEDVALUE(DimStatus[StatusName]), ",
              "                USERELATIONSHIP(FactBug[ResolutionId], DimStatus[StatusId])",
              "            )",
              "            RETURN ResStatus IN {\"fixed\", \"resolved\"}",
              "        )",
              "    ),",
              "    // Même calcul mathématique",
              "    VAR StartID = FactBug[DateSubmittedId]",
              "    VAR EndID = FactBug[DateUpdatedId]",
              "    VAR StartDate = DATE(INT(StartID / 10000), INT(MOD(StartID, 10000) / 100), MOD(StartID, 100))",
              "    VAR EndDate =   DATE(INT(EndID / 10000),   INT(MOD(EndID, 10000) / 100),   MOD(EndID, 100))",
              "    VAR Ecart = DATEDIFF(StartDate, EndDate, DAY)",
              "    ",
              "    RETURN IF(Ecart = 0, 1, Ecart)",
              ")"
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "7e63f273-4a20-49b9-9583-63cc2eceff3f",
        "fromTable": "FactBug",
        "fromColumn": "DateUpdatedId",
        "toTable": "DimCalendar",
        "toColumn": "DateId",
        "isActive": false
      },
      {
        "name": "6ba430dd-4245-4028-8413-4ca8c92ec2ff",
        "fromTable": "FactBug",
        "fromColumn": "SDC_EndDate",
        "toTable": "DimCalendar",
        "toColumn": "DateId",
        "isActive": false
      },
      {
        "name": "34bc757c-8c9c-482a-8689-ce79f2fc731e",
        "fromTable": "FactBug",
        "fromColumn": "StatusId",
        "toTable": "DimStatus",
        "toColumn": "StatusId",
        "isActive": false
      },
      {
        "name": "28b13348-deed-4cd7-9b42-1adbb3aa0a0e",
        "fromTable": "FactBug",
        "fromColumn": "CategoryId",
        "toTable": "DimCategory",
        "toColumn": "CategoryId"
      },
      {
        "name": "d52eee14-120f-4da1-a7ee-3467554fc41b",
        "fromTable": "FactBug",
        "fromColumn": "OsId",
        "toTable": "DimOs",
        "toColumn": "OsId"
      },
      {
        "name": "3b3a339c-5145-4bc9-86b3-c32f2654f6fb",
        "fromTable": "FactBug",
        "fromColumn": "PriorityId",
        "toTable": "DimPriority",
        "toColumn": "PriorityId"
      },
      {
        "name": "bd832212-0ece-4957-bf1e-7f54085253ab",
        "fromTable": "FactBug",
        "fromColumn": "ProjectId",
        "toTable": "DimProject",
        "toColumn": "ProjectId"
      },
      {
        "name": "95a93c85-350c-4d55-8e4f-23a128cc7a02",
        "fromTable": "FactBug",
        "fromColumn": "ReproducibilityId",
        "toTable": "DimReproducibility",
        "toColumn": "ReproducibilityId"
      },
      {
        "name": "2ddf4f36-8340-465f-9256-6408f12acd6d",
        "fromTable": "FactBug",
        "fromColumn": "SeverityId",
        "toTable": "DimSeverity",
        "toColumn": "SeverityId"
      },
      {
        "name": "a729ffe2-54f2-455a-9c79-3d39128254d4",
        "fromTable": "FactBug",
        "fromColumn": "SDC_StartDate",
        "toTable": "DimCalendar",
        "toColumn": "DateId",
        "isActive": false
      },
      {
        "name": "98300d58-1fd0-42cf-960c-7ab28852b8eb",
        "fromTable": "FactBug",
        "fromColumn": "DateSubmittedId",
        "toTable": "DimCalendar",
        "toColumn": "DateId"
      },
      {
        "name": "7c9806e1-9028-47bd-b4e5-cee765736437",
        "fromTable": "FactBug",
        "fromColumn": "ReporterId",
        "toTable": "DimUser",
        "toColumn": "UserId",
        "isActive": false
      },
      {
        "name": "621e7ac4-628b-4f17-ab60-7180764b2954",
        "fromTable": "FactBug",
        "fromColumn": "AssigneeId",
        "toTable": "DimUser",
        "toColumn": "UserId"
      },
      {
        "name": "3b05d8b0-6031-4c20-a6ad-5eede74d3433",
        "fromTable": "FactBug",
        "fromColumn": "ViewStatusId",
        "toTable": "DimStatus",
        "toColumn": "StatusId",
        "isActive": false
      },
      {
        "name": "b7d53d01-580a-4bc3-a5e7-758cb72979f5",
        "fromTable": "FactBug",
        "fromColumn": "ResolutionId",
        "toTable": "DimStatus",
        "toColumn": "StatusId"
      },
      {
        "name": "ff66c41f-5cc3-40e5-9f41-5420d7b403fd",
        "fromTable": "FactBug",
        "fromColumn": "VersionFixedId",
        "toTable": "DimVersion",
        "toColumn": "VersionId",
        "isActive": false
      },
      {
        "name": "490e5696-9083-4128-8775-c6825789027b",
        "fromTable": "FactBug",
        "fromColumn": "ProductVersionId",
        "toTable": "DimVersion",
        "toColumn": "VersionId"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}